### ISSUE TITLE
Add option for document expiration

### ISSUE THREAD

**Issue by oxr463** [zhaoterryy/mkdocs-git-revision-date-plugin#15]
If the published date is older than a predefined interval, then `mkdocs build` should fail, and a warning message issues for the offending document.

For example, here is a snippet from an article

```md
---
date: 2001-07-19
---

# Article Title
```

And here is the option in my `mkdocs.yml` file:

```yml
extra:
  expiration_period: 2Y
```

Then during the build phase:

```sh
mkdocs build
Error: documentation has not been update since July, 2001.
```

**Comment by zhaoterryy** [comment]
I would like to keep this plugin as simple as possible. The feature you're asking for should be a separate plugin. Thanks for the suggestion!
