### ISSUE TITLE
How can I add this to markdown

### ISSUE THREAD

**Issue by majkinetor** [zhaoterryy/mkdocs-git-revision-date-plugin#2]
I don't want to mess with theme files because then upgrading theme later might be problematic.

I have a header/footer system via mkdocs-include. Is it possible to add this in markdown directly, i.e.

footer.md
```
Last changed: {{revision_date}}
```

**Comment by zhaoterryy** [comment]
Try using `{{ git_revision_date }}`

The [`macros` plugin](https://github.com/fralau/mkdocs_macros_plugin) must be included after `git-revision-date` under plugins inside `mkdocs.yml`.

i.e., `mkdocs.yml`:
```
plugins:
  - search
  - git-revision-date
  - macros
```

This works without using the `macros` plugin as well.
