### ISSUE TITLE
{{ page.meta.revision_date }} should be type String

### ISSUE THREAD

**Issue by angelobanse** [zhaoterryy/mkdocs-git-revision-date-plugin#4]
Currently it is impossible to edit `{{ page.meta.revision_date }}` using Javascript because it is a number (`typeof=number`). I would like to change the displaying format from YYYY-MM-DD to something more user friendly such as a text like *25 January 2019* but for that `{{ page.meta.revision_date }}` should be a String in order to perform some operations such as `split()` and `concat()`.

Is there any way to change the date-format using your plugin?
Have you think about changing the type of variable from **number** to **String**?

Thanks!

**Comment by timvink** [comment]
@zhaoterryy I'm happy to provide a PR for this. 

Shall I add an option to output date as python `datetime` instead of `str`, in order not to break backwards compatibility? 

So in `mkdocs.yml`:

```
plugins:
  - git-revision-date:
      as_datetime: True
```

**Comment by zhaoterryy** [comment]
#6 closes this

**Comment by angelobanse** [comment]
Thanks! Works like a charm 😄
