### ISSUE TITLE
help with material

### ISSUE THREAD

**Issue by berot3** [zhaoterryy/mkdocs-git-revision-date-plugin#5]
Hi! I use material theme and would like to keep the footer as it is plus revision date and not completly replace it. How would I do that? 

Also, I am wondering if it would be possible to add the date at the top-right of every page?
As it says in the documentation:
> `content`: Contains the page content and table of contents for the page.

So I have to insert it somewhere there?

**Comment by timvink** [comment]
This is not really an issue with this plugin. Have a look at [mkdocs-material customization](https://squidfunk.github.io/mkdocs-material/customization/) page. 

I opened https://github.com/squidfunk/mkdocs-material/issues/1350 to support by default the date at the top of every page.
