### ISSUE TITLE
Display relative time ago

### ISSUE THREAD

**Issue by timvink** [zhaoterryy/mkdocs-git-revision-date-plugin#7]
When using `revision-date` in templates we could offer the possibility to display it relatively using the [timeago](https://github.com/hustcc/timeago) package and implementing as a custom jinja2 filter, like so:

```django hljs
<i>Updated {{ page.meta.revision_date }}</i>
<i>Updated {{ page.meta.revision_date | totimeago }}</i>
<i>Updated {{ page.meta.revision_date | totimeago('nl') }}</i>
```

Example output:

```
Updated 2019-11-28
Updated 20 hours ago
Updated 20 uren geleden
```

Would like to offer a PR!

**Comment by zhaoterryy** [comment]
As you mentioned in #8, I would like to avoid adding totimeago as a dependency.

timvink made a separate plugin for this here: https://github.com/timvink/mkdocs-date-filters-plugin

Cheers!

**Comment by timvink** [comment]
In case anyone is looking for this, I decided to go a different route in order to support localization and created a fork that offers this functionality:
https://github.com/timvink/mkdocs-git-revision-date-localized-plugin
